package com.example.demo.entity;
// Generated May 25, 2020 7:40:23 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CauHoi generated by hbm2java
 */
@Entity
@Table(name = "cau_hoi", catalog = "db_fb")
public class CauHoi implements java.io.Serializable {

	private Integer chMa;
	private Loai loai;
	private String chNoiDung;
	private int chThuTu;

	public CauHoi() {
	}

	public CauHoi(String chNoiDung, int chThuTu) {
		this.chNoiDung = chNoiDung;
		this.chThuTu = chThuTu;
	}

	public CauHoi(Loai loai, String chNoiDung, int chThuTu) {
		this.loai = loai;
		this.chNoiDung = chNoiDung;
		this.chThuTu = chThuTu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ch_ma", unique = true, nullable = false)
	public Integer getChMa() {
		return this.chMa;
	}

	public void setChMa(Integer chMa) {
		this.chMa = chMa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "l_ma")
	public Loai getLoai() {
		return this.loai;
	}

	public void setLoai(Loai loai) {
		this.loai = loai;
	}

	@Column(name = "ch_noi_dung", nullable = false, length = 200)
	public String getChNoiDung() {
		return this.chNoiDung;
	}

	public void setChNoiDung(String chNoiDung) {
		this.chNoiDung = chNoiDung;
	}

	@Column(name = "ch_thu_tu", nullable = false)
	public int getChThuTu() {
		return this.chThuTu;
	}

	public void setChThuTu(int chThuTu) {
		this.chThuTu = chThuTu;
	}

}
