package com.example.demo.entity;
// Generated May 25, 2020 7:40:23 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChiTietFeedback generated by hbm2java
 */
@Entity
@Table(name = "chi_tiet_feedback", catalog = "db_fb")
public class ChiTietFeedback implements java.io.Serializable {

	private Integer ctMa;
	private String ctText1;
	private String ctText2;
	private String ctText3;
	private String ctText4;
	private String ctText5;
	private Integer ctInt1;
	private Integer ctInt2;
	private Integer ctInt3;
	private Integer ctInt4;
	private Integer ctInt5;
	private Integer ctInt6;
	private Integer ctInt7;
	private Integer ctInt8;
	private Integer ctInt9;
	private Integer ctInt10;
	private Integer ctInt11;
	private Integer ctInt12;
	private Boolean ctBool;
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);

	public ChiTietFeedback() {
	}

	public ChiTietFeedback(String ctText1, String ctText2, String ctText3, String ctText4, String ctText5,
			Integer ctInt1, Integer ctInt2, Integer ctInt3, Integer ctInt4, Integer ctInt5, Integer ctInt6,
			Integer ctInt7, Integer ctInt8, Integer ctInt9, Integer ctInt10, Integer ctInt11, Integer ctInt12,
			Boolean ctBool, Set<Feedback> feedbacks) {
		this.ctText1 = ctText1;
		this.ctText2 = ctText2;
		this.ctText3 = ctText3;
		this.ctText4 = ctText4;
		this.ctText5 = ctText5;
		this.ctInt1 = ctInt1;
		this.ctInt2 = ctInt2;
		this.ctInt3 = ctInt3;
		this.ctInt4 = ctInt4;
		this.ctInt5 = ctInt5;
		this.ctInt6 = ctInt6;
		this.ctInt7 = ctInt7;
		this.ctInt8 = ctInt8;
		this.ctInt9 = ctInt9;
		this.ctInt10 = ctInt10;
		this.ctInt11 = ctInt11;
		this.ctInt12 = ctInt12;
		this.ctBool = ctBool;
		this.feedbacks = feedbacks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ct_ma", unique = true, nullable = false)
	public Integer getCtMa() {
		return this.ctMa;
	}

	public void setCtMa(Integer ctMa) {
		this.ctMa = ctMa;
	}

	@Column(name = "ct_text_1", length = 200)
	public String getCtText1() {
		return this.ctText1;
	}

	public void setCtText1(String ctText1) {
		this.ctText1 = ctText1;
	}

	@Column(name = "ct_text_2", length = 200)
	public String getCtText2() {
		return this.ctText2;
	}

	public void setCtText2(String ctText2) {
		this.ctText2 = ctText2;
	}

	@Column(name = "ct_text_3", length = 200)
	public String getCtText3() {
		return this.ctText3;
	}

	public void setCtText3(String ctText3) {
		this.ctText3 = ctText3;
	}

	@Column(name = "ct_text_4", length = 200)
	public String getCtText4() {
		return this.ctText4;
	}

	public void setCtText4(String ctText4) {
		this.ctText4 = ctText4;
	}

	@Column(name = "ct_text_5", length = 200)
	public String getCtText5() {
		return this.ctText5;
	}

	public void setCtText5(String ctText5) {
		this.ctText5 = ctText5;
	}

	@Column(name = "ct_int_1")
	public Integer getCtInt1() {
		return this.ctInt1;
	}

	public void setCtInt1(Integer ctInt1) {
		this.ctInt1 = ctInt1;
	}

	@Column(name = "ct_int_2")
	public Integer getCtInt2() {
		return this.ctInt2;
	}

	public void setCtInt2(Integer ctInt2) {
		this.ctInt2 = ctInt2;
	}

	@Column(name = "ct_int_3")
	public Integer getCtInt3() {
		return this.ctInt3;
	}

	public void setCtInt3(Integer ctInt3) {
		this.ctInt3 = ctInt3;
	}

	@Column(name = "ct_int_4")
	public Integer getCtInt4() {
		return this.ctInt4;
	}

	public void setCtInt4(Integer ctInt4) {
		this.ctInt4 = ctInt4;
	}

	@Column(name = "ct_int_5")
	public Integer getCtInt5() {
		return this.ctInt5;
	}

	public void setCtInt5(Integer ctInt5) {
		this.ctInt5 = ctInt5;
	}

	@Column(name = "ct_int_6")
	public Integer getCtInt6() {
		return this.ctInt6;
	}

	public void setCtInt6(Integer ctInt6) {
		this.ctInt6 = ctInt6;
	}

	@Column(name = "ct_int_7")
	public Integer getCtInt7() {
		return this.ctInt7;
	}

	public void setCtInt7(Integer ctInt7) {
		this.ctInt7 = ctInt7;
	}

	@Column(name = "ct_int_8")
	public Integer getCtInt8() {
		return this.ctInt8;
	}

	public void setCtInt8(Integer ctInt8) {
		this.ctInt8 = ctInt8;
	}

	@Column(name = "ct_int_9")
	public Integer getCtInt9() {
		return this.ctInt9;
	}

	public void setCtInt9(Integer ctInt9) {
		this.ctInt9 = ctInt9;
	}

	@Column(name = "ct_int_10")
	public Integer getCtInt10() {
		return this.ctInt10;
	}

	public void setCtInt10(Integer ctInt10) {
		this.ctInt10 = ctInt10;
	}

	@Column(name = "ct_int_11")
	public Integer getCtInt11() {
		return this.ctInt11;
	}

	public void setCtInt11(Integer ctInt11) {
		this.ctInt11 = ctInt11;
	}

	@Column(name = "ct_int_12")
	public Integer getCtInt12() {
		return this.ctInt12;
	}

	public void setCtInt12(Integer ctInt12) {
		this.ctInt12 = ctInt12;
	}

	@Column(name = "ct_bool")
	public Boolean getCtBool() {
		return this.ctBool;
	}

	public void setCtBool(Boolean ctBool) {
		this.ctBool = ctBool;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chiTietFeedback")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

}
