package com.example.demo.entity;
// Generated May 25, 2020 7:40:23 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "db_fb")
public class Feedback implements java.io.Serializable {

	private Integer fbMa;
	private ChiTietFeedback chiTietFeedback;
	private Loai loai;
	private LopHoc lopHoc;
	private TaiKhoan taiKhoan;

	public Feedback() {
	}

	public Feedback(ChiTietFeedback chiTietFeedback, Loai loai, LopHoc lopHoc, TaiKhoan taiKhoan) {
		this.chiTietFeedback = chiTietFeedback;
		this.loai = loai;
		this.lopHoc = lopHoc;
		this.taiKhoan = taiKhoan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fb_ma", unique = true, nullable = false)
	public Integer getFbMa() {
		return this.fbMa;
	}

	public void setFbMa(Integer fbMa) {
		this.fbMa = fbMa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ct_ma")
	public ChiTietFeedback getChiTietFeedback() {
		return this.chiTietFeedback;
	}

	public void setChiTietFeedback(ChiTietFeedback chiTietFeedback) {
		this.chiTietFeedback = chiTietFeedback;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "l_ma")
	public Loai getLoai() {
		return this.loai;
	}

	public void setLoai(Loai loai) {
		this.loai = loai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lh_ma")
	public LopHoc getLopHoc() {
		return this.lopHoc;
	}

	public void setLopHoc(LopHoc lopHoc) {
		this.lopHoc = lopHoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email")
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

}
