package com.example.demo.entity;
// Generated May 25, 2020 7:40:23 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loai generated by hbm2java
 */
@Entity
@Table(name = "loai", catalog = "db_fb")
public class Loai implements java.io.Serializable {

	private Integer LMa;
	private String LTen;
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
	private Set<CauHoi> cauHois = new HashSet<CauHoi>(0);

	public Loai() {
	}

	public Loai(String LTen, Set<Feedback> feedbacks, Set<CauHoi> cauHois) {
		this.LTen = LTen;
		this.feedbacks = feedbacks;
		this.cauHois = cauHois;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "l_ma", unique = true, nullable = false)
	public Integer getLMa() {
		return this.LMa;
	}

	public void setLMa(Integer LMa) {
		this.LMa = LMa;
	}

	@Column(name = "l_ten", length = 50)
	public String getLTen() {
		return this.LTen;
	}

	public void setLTen(String LTen) {
		this.LTen = LTen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loai")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loai")
	public Set<CauHoi> getCauHois() {
		return this.cauHois;
	}

	public void setCauHois(Set<CauHoi> cauHois) {
		this.cauHois = cauHois;
	}

}
