package com.example.demo.entity;
// Generated May 25, 2020 7:40:23 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LopHoc generated by hbm2java
 */
@Entity
@Table(name = "lop_hoc", catalog = "db_fb")
public class LopHoc implements java.io.Serializable {

	private Integer lhMa;
	private KhoaHoc khoaHoc;
	private String lhTen;
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
	private Set<DanhSachLopHoc> danhSachLopHocs = new HashSet<DanhSachLopHoc>(0);

	public LopHoc() {
	}

	public LopHoc(KhoaHoc khoaHoc, String lhTen, Set<Feedback> feedbacks, Set<DanhSachLopHoc> danhSachLopHocs) {
		this.khoaHoc = khoaHoc;
		this.lhTen = lhTen;
		this.feedbacks = feedbacks;
		this.danhSachLopHocs = danhSachLopHocs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "lh_ma", unique = true, nullable = false)
	public Integer getLhMa() {
		return this.lhMa;
	}

	public void setLhMa(Integer lhMa) {
		this.lhMa = lhMa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kh_ma")
	public KhoaHoc getKhoaHoc() {
		return this.khoaHoc;
	}

	public void setKhoaHoc(KhoaHoc khoaHoc) {
		this.khoaHoc = khoaHoc;
	}

	@Column(name = "lh_ten", length = 100)
	public String getLhTen() {
		return this.lhTen;
	}

	public void setLhTen(String lhTen) {
		this.lhTen = lhTen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lopHoc")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lopHoc")
	public Set<DanhSachLopHoc> getDanhSachLopHocs() {
		return this.danhSachLopHocs;
	}

	public void setDanhSachLopHocs(Set<DanhSachLopHoc> danhSachLopHocs) {
		this.danhSachLopHocs = danhSachLopHocs;
	}

}
