package com.example.demo.entity;
// Generated May 25, 2020 7:40:23 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaiKhoan generated by hbm2java
 */
@Entity
@Table(name = "tai_khoan", catalog = "db_fb")
public class TaiKhoan implements java.io.Serializable {

	private String email;
	private UserRole userRole;
	private String tkDiaChi;
	private String tkGioiTinh;
	private String tkHovaTen;
	private String tkPassword;
	private String tkSdt;
	private String tkTrangThai;
	private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
	private Set<DanhSachLopHoc> danhSachLopHocs = new HashSet<DanhSachLopHoc>(0);

	public TaiKhoan() {
	}

	public TaiKhoan(String email) {
		this.email = email;
	}

	public TaiKhoan(String email, UserRole userRole, String tkDiaChi, String tkGioiTinh, String tkHovaTen,
			String tkPassword, String tkSdt, String tkTrangThai, Set<Feedback> feedbacks,
			Set<DanhSachLopHoc> danhSachLopHocs) {
		this.email = email;
		this.userRole = userRole;
		this.tkDiaChi = tkDiaChi;
		this.tkGioiTinh = tkGioiTinh;
		this.tkHovaTen = tkHovaTen;
		this.tkPassword = tkPassword;
		this.tkSdt = tkSdt;
		this.tkTrangThai = tkTrangThai;
		this.feedbacks = feedbacks;
		this.danhSachLopHocs = danhSachLopHocs;
	}

	@Id

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ur_ma")
	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	@Column(name = "tk_dia_chi", length = 100)
	public String getTkDiaChi() {
		return this.tkDiaChi;
	}

	public void setTkDiaChi(String tkDiaChi) {
		this.tkDiaChi = tkDiaChi;
	}

	@Column(name = "tk_gioi_tinh", length = 3)
	public String getTkGioiTinh() {
		return this.tkGioiTinh;
	}

	public void setTkGioiTinh(String tkGioiTinh) {
		this.tkGioiTinh = tkGioiTinh;
	}

	@Column(name = "tk_hova_ten", length = 100)
	public String getTkHovaTen() {
		return this.tkHovaTen;
	}

	public void setTkHovaTen(String tkHovaTen) {
		this.tkHovaTen = tkHovaTen;
	}

	@Column(name = "tk_password", length = 20)
	public String getTkPassword() {
		return this.tkPassword;
	}

	public void setTkPassword(String tkPassword) {
		this.tkPassword = tkPassword;
	}

	@Column(name = "tk_sdt", length = 100)
	public String getTkSdt() {
		return this.tkSdt;
	}

	public void setTkSdt(String tkSdt) {
		this.tkSdt = tkSdt;
	}

	@Column(name = "tk_trang_thai", length = 10)
	public String getTkTrangThai() {
		return this.tkTrangThai;
	}

	public void setTkTrangThai(String tkTrangThai) {
		this.tkTrangThai = tkTrangThai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taiKhoan")
	public Set<Feedback> getFeedbacks() {
		return this.feedbacks;
	}

	public void setFeedbacks(Set<Feedback> feedbacks) {
		this.feedbacks = feedbacks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taiKhoan")
	public Set<DanhSachLopHoc> getDanhSachLopHocs() {
		return this.danhSachLopHocs;
	}

	public void setDanhSachLopHocs(Set<DanhSachLopHoc> danhSachLopHocs) {
		this.danhSachLopHocs = danhSachLopHocs;
	}

}
