package com.example.demo.entity;
// Generated May 25, 2020 7:40:23 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "db_fb")
public class UserRole implements java.io.Serializable {

	private Integer urMa;
	private String urRole;
	private Set<TaiKhoan> taiKhoans = new HashSet<TaiKhoan>(0);

	public UserRole() {
	}

	public UserRole(String urRole, Set<TaiKhoan> taiKhoans) {
		this.urRole = urRole;
		this.taiKhoans = taiKhoans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ur_ma", unique = true, nullable = false)
	public Integer getUrMa() {
		return this.urMa;
	}

	public void setUrMa(Integer urMa) {
		this.urMa = urMa;
	}

	@Column(name = "ur_role", length = 10)
	public String getUrRole() {
		return this.urRole;
	}

	public void setUrRole(String urRole) {
		this.urRole = urRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	public Set<TaiKhoan> getTaiKhoans() {
		return this.taiKhoans;
	}

	public void setTaiKhoans(Set<TaiKhoan> taiKhoans) {
		this.taiKhoans = taiKhoans;
	}

}
